### ISSUE TITLE
please give me some adevice, thanks

### ISSUE THREAD

**Issue by kinpol** [yoni2356/h264-transmitter#1]
$ node video-test-player.js
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: connect ECONNREFUSED 192.168.1.215:8031
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)

**Comment by yoni2356** [comment]
Hey man, basically this repo is my try on live-streaming via websockets.
Basically your'e not supposed to live stream with websockets, since its not a live-streaming protocol,
there are many others like MPEG-DASH and WebRTC that exist for live streaming.

Regarding your issue, maybe this thread could help:
https://stackoverflow.com/questions/14168433/node-js-error-connect-econnrefused

Closing this repo now
